version: '3'
name: 
services:
  dsb-data-loader:
    build:
      context: .
      dockerfile: dockerfile.dsb-data-loader
    image: cdradmin/dsb-data-loader:1.24.0
    container_name: dsb-data-loader
    env_file: .env.docker
    depends_on:
      - mongodb
    networks:
      - app-network

  dsb-test-data-server:
    build:
      context: .
      dockerfile: dockerfile.dsb-test-data-server
    image: cdradmin/dsb-test-data-server:1.24.0
    container_name: dsb-test-data-server
    restart: unless-stopped
    env_file: .env.docker
    depends_on:
      - mongodb
    ports:
      - "3005:3005"
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file: .env.docker
    volumes:     
      - dbdata:/usr/local/var/mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: