version: '3'

services:
  dsb-data-loader:
    build:
      context: .
      dockerfile: dockerfile.dsb-data-loader
    image: cdradmin/dsb-data-loader:1.24.0
    container_name: dsb-data-loader
    env_file: .env.docker
    depends_on:
      - mongodb
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      # Set DATA_IS_SINGLE_DOCUMENT=True will NOT populate the database
      # The entire database has to be a single document with a schema as per testdata-cli project
      # https://github.com/ConsumerDataStandardsAustralia/testdata-cli/blob/master/src/schema/cdr-test-data-schema.json
      - DATA_IS_SINGLE_DOCUMENT=$DATA_IS_SINGLE_DOCUMENT
      - SINGLE_COLLECTION_NAME=$SINGLE_COLLECTION_NAME

      # Set DATA_IS_SINGLE_DOCUMENT=False will populate the database with the data in load-test-data\input
      # The CUSTOMER_COLLECTION_NAME and PLAN_COLLECTION_NAME are being used. This is a good approach for larger datasets.
      # This   
      - CUSTOMER_COLLECTION_NAME=$CUSTOMER_COLLECTION_NAME
      - PLAN_COLLECTION_NAME=$PLAN_COLLECTION_NAME
    networks:
      - app-network

  dsb-test-data-server:
    build:
      context: .
      dockerfile: dockerfile.dsb-test-data-server
    image: cdradmin/dsb-test-data-server:1.24.0
    container_name: dsb-test-data-server
    restart: unless-stopped
    env_file: .env.docker
    depends_on:
      - mongodb
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD  
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - CUSTOMER_COLLECTION_NAME=$CUSTOMER_COLLECTION_NAME
      - PLAN_COLLECTION_NAME=$PLAN_COLLECTION_NAME  
      - SINGLE_COLLECTION_NAME=$SINGLE_COLLECTION_NAME    
    ports:
      - "3005:3005"
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file: .env.docker
    volumes:     
      - dbdata:/usr/local/var/mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network  

networks:
  app-network:
    name: dsb-net
    driver: bridge

volumes:
  dbdata:
  node_modules: